version: '3'
services:
  #######################################################
  #  EventStoreDB - Event Store
  #######################################################
  mongo:
    image: mongo:5
    ports:
      - '27017:27017'
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
