/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: y9bx1e/dkKoQ6cZLYfVReBKjL6maRcGBzOTM4OXOp3+ABIAtvVRDnGf7o5QgfQW0hkzseDc+ytkmNCIBMgbt3w==
 */

/* eslint-disable */
// tslint:disable

import Cart from './cart';

interface CartItem {
  cartId: Cart['id'];
  content: string | null;
  createdAt: Date;
  /**
   * @default 0
   */
  discount: number;
  /**
   * @default nextval('ecommerce.cart_item_id_seq'::regclass)
   */
  id: number & { readonly __brand?: 'cart_item_id' };
  /**
   * @default 0
   */
  price: number;
  productId: number;
  /**
   * @default 0
   */
  quantity: number;
  sku: string;
  updatedAt: Date | null;
}
export default CartItem;

interface CartItem_InsertParameters {
  cartId: Cart['id'];
  content?: string | null;
  createdAt: Date;
  /**
   * @default 0
   */
  discount?: number;
  /**
   * @default nextval('ecommerce.cart_item_id_seq'::regclass)
   */
  id?: number & { readonly __brand?: 'cart_item_id' };
  /**
   * @default 0
   */
  price?: number;
  productId: number;
  /**
   * @default 0
   */
  quantity?: number;
  sku: string;
  updatedAt?: Date | null;
}
export type { CartItem_InsertParameters };
