/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xibdKSxep2416J23fGL0QDYPpKlsLIp3ogXBK7GvIQupFAEqIQQvdgUvSqwhysKoVbEO33ET5JoDFk8nGnD6Gw==
 */

/* eslint-disable */
// tslint:disable

interface Cart {
  /**
   * @default NULL::character varying
   */
  city: string | null;
  content: string | null;
  /**
   * @default NULL::character varying
   */
  country: string | null;
  createdAt: Date;
  email: string | null;
  /**
   * @default NULL::character varying
   */
  firstName: string | null;
  /**
   * @default nextval('ecommerce.cart_id_seq'::regclass)
   */
  id: number & { readonly __brand?: 'cart_id' };
  /**
   * @default NULL::character varying
   */
  lastName: string | null;
  /**
   * @default NULL::character varying
   */
  line1: string | null;
  /**
   * @default NULL::character varying
   */
  line2: string | null;
  /**
   * @default NULL::character varying
   */
  middleName: string | null;
  mobile: string | null;
  /**
   * @default NULL::character varying
   */
  province: string | null;
  sessionId: string;
  /**
   * @default 0
   */
  status: number;
  updatedAt: Date | null;
  userId: number | null;
}
export default Cart;

interface Cart_InsertParameters {
  /**
   * @default NULL::character varying
   */
  city?: string | null;
  content?: string | null;
  /**
   * @default NULL::character varying
   */
  country?: string | null;
  createdAt: Date;
  email?: string | null;
  /**
   * @default NULL::character varying
   */
  firstName?: string | null;
  /**
   * @default nextval('ecommerce.cart_id_seq'::regclass)
   */
  id?: number & { readonly __brand?: 'cart_id' };
  /**
   * @default NULL::character varying
   */
  lastName?: string | null;
  /**
   * @default NULL::character varying
   */
  line1?: string | null;
  /**
   * @default NULL::character varying
   */
  line2?: string | null;
  /**
   * @default NULL::character varying
   */
  middleName?: string | null;
  mobile?: string | null;
  /**
   * @default NULL::character varying
   */
  province?: string | null;
  sessionId: string;
  /**
   * @default 0
   */
  status?: number;
  updatedAt?: Date | null;
  userId?: number | null;
}
export type { Cart_InsertParameters };
