/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Th4HMdHeUPmTIANaulYByY22NeagyeH6Q7D4brKBw2ESBdZX4m0BaRyk+r15DxApW+N/RqZXshECcAVqiQBAnQ==
 */

/* eslint-disable */
// tslint:disable

import Cart, {Cart_InsertParameters} from './cart'
import CartItem, {CartItem_InsertParameters} from './cart_item'

interface DatabaseSchema {
  cart: {record: Cart, insert: Cart_InsertParameters};
  cart_item: {record: CartItem, insert: CartItem_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Cart,
  Cart_InsertParameters,
  CartItem,
  CartItem_InsertParameters,
}
