version: '3'

services:
  #######################################################
  #  EventStoreDB
  #######################################################
  eventstoredb:
    image: eventstore/eventstore:24.10.0-bookworm-slim
    # use this image if you're running ARM-based proc like Apple M1
    # image: eventstore/eventstore:24.10.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_NODE_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - esdb_network

  #######################################################
  #  MongoDB
  #######################################################
  mongodb:
    image: mongo:6.0.12
    # environment:
    #     MONGO_INITDB_ROOT_USERNAME: root
    #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - mongodb_network

  #######################################################
  #  PostgreSQL
  #######################################################
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      - postgresql_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgresql_network

networks:
  esdb_network:
    driver: bridge
  postgresql_network:
    driver: bridge
  mongodb_network:
    driver: bridge

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongodb-data:
